# We have 2 stage Test and Deploy
stages:
  - test
  - deploy

# Config cache
cache:
  paths:
    - node_modules/

# Test job
test:
  # Docker image
  image: node:14
  # Attach Test job to Test stage
  stage: test
  # Config to use GitLab Shared Runner with Executor Docker
  tags:
    - gitlab-org-docker
  script:
    - echo "MYSQL_USERNAME"=$MYSQL_USERNAME > .env.test
    - echo "MYSQL_PASSWORD"=$MYSQL_PASSWORD >> .env.test
    - echo "MYSQL_DATABASE"=$MYSQL_DATABASE_TEST >> .env.test
    - echo "MYSQL_HOST"=$MYSQL_HOST >> .env.test
    - echo "S3_ACCESS_KEY"=$S3_ACCESS_KEY >> .env.test
    - echo "S3_SECRET_KEY"=$S3_SECRET_KEY >> .env.test
    - echo "S3_BUCKET"=$S3_BUCKET >> .env.test
    - echo "S3_REGION"=$S3_REGION >> .env.test
    - echo "S3_URL"=$S3_URL >> .env.test
    - echo "JWT_SECRET"=$JWT_SECRET >> .env.test
    - npm i
    - NODE_ENV=test npx sequelize db:drop
    - NODE_ENV=test npx sequelize db:create
    - NODE_ENV=test npx sequelize db:migrate
    - npm run test
    - NODE_ENV=test npx sequelize db:drop
  # Defines the names of branches and tags the job runs for
  only:
    - ci-cd-sequelize

# Deploy job
deploy:
  type: deploy
  # Attach Deploy job to Deploy stage
  stage: deploy
  # Config to use our Runner with Executor Shell
  tags:
    - ci-cd-sequelize
  script:
    # Only copy changed files to project folder
    - cp -r -u * $PROJECT_DIR
    - cd $PROJECT_DIR
    - echo "MYSQL_USERNAME"=$MYSQL_USERNAME > .env.production
    - echo "MYSQL_PASSWORD"=$MYSQL_PASSWORD >> .env.production
    - echo "MYSQL_DATABASE"=$MYSQL_DATABASE_PRODUCTION >> .env.production
    - echo "MYSQL_HOST"=$MYSQL_HOST >> .env.production
    - echo "S3_ACCESS_KEY"=$S3_ACCESS_KEY >> .env.production
    - echo "S3_SECRET_KEY"=$S3_SECRET_KEY >> .env.production
    - echo "S3_BUCKET"=$S3_BUCKET >> .env.production
    - echo "S3_REGION"=$S3_REGION >> .env.production
    - echo "S3_URL"=$S3_URL >> .env.production
    - echo "JWT_SECRET"=$JWT_SECRET >> .env.production
    - npm i
    - NODE_ENV=production npx sequelize db:create
    - NODE_ENV=production npx sequelize db:migrate

    # Restart NodeJS service
    - npm run stop
    - npm run start
  only:
    - ci-cd-sequelize
